/**
 * Configuration unique de l'API Django utilisée par les services frontend.
 */
export const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000').replace(/\/$/, '')

export const API_ENDPOINTS = {
  auth: {
    login: '/api/auth/login/',
    register: '/api/auth/register/',
    refresh: '/api/auth/token/refresh/',
    logout: '/api/auth/logout/',
    profile: '/api/auth/profile/',
    profilePhoto: '/api/auth/profile/photo/',
  },
  location: '/api/location/',
  categories: '/api/categories/',
  services: '/api/services/',
  search: '/api/recherche/',
  searchIntelligente: '/api/recherche/intelligente/',
  serviceOffers: (id) => `/api/services/${id}/prestataires/`,
  providerOffers: '/api/prestataire-services/',
  providers: '/api/prestataires/',
  provider: (id) => `/api/prestataires/${id}/`,
  providerProfile: '/api/profil/prestataire/',
  reviews: '/api/avis/',
  review: (id) => `/api/avis/${id}/`,
  requests: '/api/demande-prestation/',
  request: (id) => `/api/demande-prestation/${id}/`,
  cancelRequest: (id) => `/api/demande-prestation/${id}/annuler/`,
  acceptRequest: (id) => `/api/demande-prestation/${id}/accepter/`,
  rejectRequest: (id) => `/api/demande-prestation/${id}/refuser/`,
  completeRequest: (id) => `/api/demande-prestation/${id}/terminer/`,
  quoteRequests: '/api/demandes/',
  quoteResponses: '/api/reponses/',
  acceptQuoteResponse: (id) => `/api/reponses/${id}/accepter/`,
  disponibilites: '/api/disponibilites/',
  disponibilite: (id) => `/api/disponibilites/${id}/`,
  providerDisponibilites: (prestataireId) => `/api/prestataires/${prestataireId}/disponibilites/`,
  providerCreneauxDisponibles: (prestataireId) => `/api/prestataires/${prestataireId}/creneaux-disponibles/`,
  rendezVous: '/api/rendez-vous/',
  rendezVousDetail: (id) => `/api/rendez-vous/${id}/`,
  confirmRendezVous: (id) => `/api/rendez-vous/${id}/confirmer/`,
  refuseRendezVous: (id) => `/api/rendez-vous/${id}/refuser/`,
  cancelRendezVous: (id) => `/api/rendez-vous/${id}/annuler/`,
  completeRendezVous: (id) => `/api/rendez-vous/${id}/terminer/`,
  verificationDocument: '/api/verification/document/',
  verificationDocuments: '/api/verification/documents/',
  verificationDocumentFichier: (id) => `/api/verification/document/${id}/fichier/`,
  monWallet: '/api/wallet/mon-wallet/',
  mesTransactions: '/api/wallet/mes-transactions/',
  mesRetraits: '/api/wallet/mes-retraits/',
  mesPaiements: '/api/wallet/mes-paiements/',
  statutPaiement: (id) => `/api/wallet/mes-paiements/${id}/statut/`,
  adminDocuments: '/api/verification/admin/documents/',
  adminDocumentValider: (id) => `/api/verification/admin/documents/${id}/valider/`,
  adminDocumentRejeter: (id) => `/api/verification/admin/documents/${id}/rejeter/`,
  adminAvis: '/api/avis/',
  adminAvisApprouver: (id) => `/api/avis/${id}/approuver/`,
  adminAvisBloquer: (id) => `/api/avis/${id}/bloquer/`,
  adminPaiements: '/api/wallet/admin/paiements/',
  adminRetraits: '/api/wallet/admin/retraits/',
  adminTransactions: '/api/wallet/admin/transactions/',
  adminDashboard: '/api/admin/dashboard/',
  adminActivite: '/api/admin/activite/',
  adminUtilisateurs: '/api/admin/utilisateurs/',
  adminUtilisateurStatut: (id) => `/api/admin/utilisateurs/${id}/statut/`,
  adminClients: '/api/admin/clients/',
  adminPrestataires: '/api/admin/prestataires/',
  adminDemandes: '/api/admin/demandes/',
  adminDevis: '/api/admin/devis/',
  adminRendezVous: '/api/admin/rendez-vous/',
  adminLocalisations: '/api/admin/localisations/',
  adminPrestataireScoreConfiance: (id) => `/api/admin/prestataires/${id}/score-confiance/`,
  signalements: '/api/signalements/',
  signalementPrendreEnCharge: (id) => `/api/signalements/${id}/prendre_en_charge/`,
  signalementTraiter: (id) => `/api/signalements/${id}/traiter/`,
  signalementRejeter: (id) => `/api/signalements/${id}/rejeter/`,
  litiges: '/api/litiges/',
  litige: (id) => `/api/litiges/${id}/`,
  litigeAjouterPreuve: (id) => `/api/litiges/${id}/preuves/`,
  litigePreuveFichier: (id) => `/api/litiges/preuves/${id}/fichier/`,
  litigeAnalyse: (id) => `/api/litiges/${id}/analyse/`,
  litigePrendreEnCharge: (id) => `/api/litiges/${id}/prendre_en_charge/`,
  litigeResoudre: (id) => `/api/litiges/${id}/resoudre/`,
  litigeRejeter: (id) => `/api/litiges/${id}/rejeter/`,
  litigeDemanderReprise: (id) => `/api/litiges/${id}/demander-reprise/`,
  litigeConfirmerReprise: (id) => `/api/litiges/${id}/confirmer-reprise/`,
  litigeReattribuer: (id) => `/api/litiges/${id}/reattribuer/`,
  diagnostic: '/api/diagnostic/',
  category: (id) => `/api/categories/${id}/`,
  service: (id) => `/api/services/${id}/`,
  notifications: '/api/notifications/',
  readNotification: (id) => `/api/notifications/${id}/marquer-lue/`,
  readAllNotifications: '/api/notifications/marquer-toutes-lues/',
  messages: '/api/messages/',
  message: (id) => `/api/messages/${id}/`,
}
